version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: VisemoServices/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./VisemoServices/view
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  ai:
    build:
      context: ./VisemoServices/ai_files/FastAPI_Endpoint
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
