name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./VisemoServices/View
        run: npm install

      - name: Set environment variables
        run: echo "REACT_APP_API_URL=https://visemo-app-dtameucff0cbocce.southeastasia-01.azurewebsites.net/api" >> $GITHUB_ENV

      - name: Build React app
        working-directory: ./VisemoServices/View
        run: npm run build

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BAY_0D5523F00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "VisemoServices/View"
          output_location: "VisemoServices/View/build"
