name: Build and deploy ASP.Net Core app to Azure Web App - Visemo-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      #Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      #Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      #Restore dependencies
      - name: Restore dependencies
        run: dotnet restore VisemoServices/VisemoServices.csproj

      #Build the project
      - name: Build
        run: dotnet build VisemoServices/VisemoServices.csproj --configuration Release --no-restore

      #Publish the project
      - name: Publish
        run: dotnet publish VisemoServices/VisemoServices.csproj -c Release -o publish /p:PublishDir=publish/

      #Upload the publish artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish/

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      #Download the build artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      #Login to Azure using Service Principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      #Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Visemo-app'
          slot-name: 'Production'
          package: .



# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy ASP.Net Core app to Azure Web App - Visemo-app

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: windows-latest
#     permissions:
#       contents: read This is required for actions/checkout

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up .NET Core
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: '8.x'

#       - name: Build with dotnet
#         run: dotnet build --configuration Release

#       - name: dotnet publish
#         run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: .net-app
#           path: ${{env.DOTNET_ROOT}}/myapp

#   deploy:
#     runs-on: windows-latest
#     needs: build
#     permissions:
#       id-token: write This is required for requesting the JWT
#       contents: read This is required for actions/checkout

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: .net-app
      
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_78AD4C0F82BA4788B06DE09819111377 }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6F0D1B7E4594B8EAD34408B49D5AEC7 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E37844E226FF4348A09C9398B0FAE512 }}

#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'Visemo-app'
#           slot-name: 'Production'
#           package: .
          